substitutions:
  status_three_way_valve: Status 3-weg klep
  status_three_way_valve_2: Status 3-weg klep 2
  dhw_temp: SWW huidige temp
  status_dhw_forced: Status SWW geforceerd
  dhw_flow_temp_drop: SWW max temp hysterese
  status_prohibit_dhw: Status SWW verboden
  heatpump_number_set_dhw_temperature: SWW setpoint
  dhw_flow_temp_target: SWW setpoint waarde
  status_dhw: Status SWW value
  esp_ip: Esp IP
  internal_esp_temperature: Esp Interne temperatuur
  esp_sidd: Esp SSID
  uptime: Esp Uptime
  esp_version: Esp Versie
  restart_button: Esp herstart
  status_in1_request: Status In1 thermostaat
  status_in6_request: Status In6 thermostaat 2
  heatpump_select_dhw_mode: Set SWW modus
  of: "Uit"
  normal: Normaal
  eco: Eco
  version: ESP versie
  led_brightness: Set Led helderheid
  led_switch: Set Led schakelaar
  heatpump_switch_force_dhw: Set forceer sww
  heatpump_switch_power_mode: Set warmtepomp Aan/uit
  heatpump_switch_holiday: Set vakantie modus
  wifi_signal_proc: WiFi Signaal %
  wifi_signal_db: WiFi Signaal dB
  heatpump_number_z1_set_flow_temperature: Zone 1 V/K setpoint
  z1_flow_temp_target: Zone 1 V/K setpoint waarde
  status_prohibit_cool_z1: Status Zone 1 verboden koelen
  status_prohibit_heating_z1: Status zone 1 verboden verwarmen
  heatpump_number_z1_set_room_temperature: Zone 1 ruimte setpoint
  z1_room_temp_target: Zone 1 ruimte setpoint waarde
  z1_room_temp: Zone 1 ruimte temp
  heatpump_number_z2_set_flow_temperature: Zone 2 V/K setpoint
  z2_flow_temp_target: Zone 2 V/K setpoint waarde
  status_prohibit_cool_z2: Status zone 2 verboden koelen
  status_prohibit_heating_z2: Status zone 2 verboden verwarmen
  heatpump_number_z2_set_room_temperature: Zone 2 ruimte setpoint
  z2_room_temp_target: Zone 2 ruimte setpoint waarde
  z2_room_temp: Zone 2 ruimte temp
  boiler_flow_temp: Boiler aanvoer temp
  boiler_return_temp: Boiler retour temp
  status_booster: Status booster heater
  compressor_frequency: kompressor frequentie
  controller_version_text: controller versie
  cool_consumed: Koelen verbruikt
  cool_cop: Koelen cop
  cool_delivered: Koelen geleverd
  status_defrost: Status ontdooi
  dhw_consumed: Sww verbruikt
  dhw_cop: Sww cop
  dhw_delivered: Sww geleverd
  hp_feed_temp: Aanvoer temp
  flow_rate: Flow waarde
  heat_source_text: Verwarmings bron
  heatpump: warmtepomp
  immersion_heater: immersion heater
  booster_heater: booster heater
  immersion_and_booster_heater: immersion and booster heater
  boiler: boiler
  heating_consumed: Verwarmen verbruikt
  heating_cop: Verwarmen cop
  heating_delivered: Verwarmen geleverd
  status_holiday: Status vakantie
  status_immersion: Status externe heater
  legionella_prevention_temp: legionella preventie temp
  heatpump_select_operating_mode: Werking mode
  heat_target_temperature: Verwarmen Doel
  heat_flow_temperature: Verwarmen Flow
  heat_compensation_curve: Verwarmen Curve
  cool_target_temperature: Koelen Doel
  cool_flow_temperature: Koelen Flow
  runtime: Bedrijfsuren
  status_operation: Status Bedrijf
  output_power: Afgegeven vermogen
  outside_temp: Buiten temp
  hp_refrigerant_temp: Koelmiddel temp
  hp_return_temp: Retour temp
  sh_flow_temp_target: sh_flow_temp_doel
  status_water_pump: Status water pomp
  status_water_pump_2: Status water pomp 2