substitutions:
  status_three_way_valve: Valvola 3 Vie
  status_three_way_valve_2: Valvola 3 Vie 2
  heatpump_climate_dhw: ACS T. Attuale
  dhw_temp: ACS T. Superiore
  dhw_secondary_temp: ACS T. Inferiore
  status_dhw_forced: ACS Forzata
  dhw_flow_temp_drop: ACS Isteresi
  status_prohibit_dhw: ACS Proibita
  heatpump_number_set_dhw_temperature: ACS T. Desiderata
  dhw_flow_temp_target: ACS T. Mandata
  status_dhw: ACS
  esp_ip: ESP IP
  internal_esp_temperature: ESP T. Interna
  esp_sidd: ESP SSID
  uptime: ESP Uptime
  esp_version: ESP Versione
  restart_button: ESP Riavvio
  status_in1_request: Termost. Zona 1 (IN1)
  status_in6_request: Termost. Zona 2 (IN6)
  status_in5_request: Termost.Esterno (IN5)
  heatpump_select_dhw_mode: ACS Modo
  of: "Spento"
  normal: Normale
  eco: Eco
  version: ESP Versione
  led_brightness: LED Luminosità
  led_switch: LED
  heatpump_switch_force_dhw: Forza ACS
  heatpump_switch_power_mode: PDC
  heatpump_switch_holiday: Modalità Vacanza
  wifi_signal_proc: WiFi Segnale %
  wifi_signal_db: WiFi Segnale dB
  heatpump_number_z1_set_flow_temperature: Zona 1 C/F Setpoint
  z1_flow_temp_target: Zona 1 C/F T. Mandata
  status_prohibit_cool_z1: Zona 1 Raffreddamento Proibito
  status_prohibit_heating_z1: Zona 1 Riscaldamento Proibito
  heatpump_number_z1_set_room_temperature: Zona 1 T. Ambiente
  heatpump_climate_z1_room_climate: Zona 1 Climate
  heatpump_climate_z1_flow_temperature: Zona 1 Mandata Climate
  z1_room_temp_target: Zona 1 T. Ambiente Desiderata
  z1_room_temp: Zona 1 T. Ambiente
  heatpump_number_z2_set_flow_temperature: Zona 2 C/F setpoint
  z2_flow_temp_target: Zona 2 C/F T. Mandata
  status_prohibit_cool_z2: Zona 2 Raffreddamento Proibito
  status_prohibit_heating_z2: Zona 2 Riscaldamento Proibito
  heatpump_number_z2_set_room_temperature: Zona 2 T. Ambiente
  heatpump_climate_z2_room_climate: Zona 2 Climate
  heatpump_climate_z2_flow_temperature: Zona 2 flow Climate
  z2_room_temp_target: Zona 2 T. Ambiente Desiderata
  z2_room_temp: Zona 2 Ambiente Temp
  boiler_flow_temp: Caldaia T. Mandata
  boiler_return_temp: Caldaia T. Ritorno
  status_booster: Riscaldatore Booster
  compressor_frequency: Frequenza Compressore
  controller_version_text: Versione Controller
  cool_consumed: Cool Consumed
  cool_cop: Cool COP
  cool_delivered: Cool Delivered
  status_defrost: Defrost
  dhw_consumed: ACS Consumed
  dhw_cop: ACS COP
  dhw_delivered: ACS Delivered
  hp_feed_temp: Feed Temp
  flow_rate: Flow Rate
  heat_source_text: Heat Source
  heatpump: Heatpump
  immersion_heater: Immersion Heater
  booster_heater: Booster Heater
  immersion_and_booster_heater: Immersion and Booster Heater
  boiler: Caldaia
  heating_consumed: Heating Consumed
  heating_cop: Heating COP
  heating_delivered: Heating Delivered
  status_holiday: Holiday Mode
  status_immersion: Immersion Heater
  legionella_prevention_temp: Legionella Prevention Temp
  heatpump_select_operating_mode: Operating mode
  heat_target_temperature: Heat Target Temperature
  heat_flow_temperature: Heat Flow Temperature
  heat_compensation_curve: Heat Compensation Curve
  cool_target_temperature: Cool Target Temperature
  cool_flow_temperature: Cool Flow Temperature
  runtime: Operating Runtime
  status_operation: Operation Mode
  output_power: Output Power
  computed_output_power: Estimated Output Power
  outside_temp: Outside Temp
  hp_refrigerant_temp: Refrigerant Liquid Temp
  hp_refrigerant_condensing_temp: Refrigerant Condensing Temp
  hp_return_temp: Return Temp
  status_water_pump: Water Pump Status
  status_water_pump_2: Water Pump 2 Status
