text_sensor:
  - platform: ecodan
    status_prohibit_heating_z2:
      id: status_prohibit_heating_z2
      name: Zone 2 prohibit heating status
    status_prohibit_cool_z2:
      id: status_prohibit_cool_z2
      name: Zone 2 prohibit cooling status

number:
  - platform: template
    name: Zone 2 room setpoint
    id: heatpump_number_z2_set_room_temperature
    mode: slider
    entity_category: config
    optimistic: true
    min_value: 8
    max_value: 28
    step: 0.5
    initial_value: 20
    restore_value: yes
    unit_of_measurement: °C
    set_action:
      then:
        - lambda: |-
            id(ecodan_instance).set_room_temperature(x, esphome::ecodan::SetZone::ZONE_2);

  - platform: template
    name: Zone 2 H/C setpoint
    id: heatpump_number_z2_set_flow_temperature
    mode: slider
    entity_category: config
    optimistic: true
    min_value: 5
    max_value: 60
    step: 0.5
    initial_value: 30
    restore_value: yes
    unit_of_measurement: °C
    set_action:
      then:
        - lambda: |-
            id(ecodan_instance).set_flow_target_temperature(x, esphome::ecodan::SetZone::ZONE_2);

sensor:
  - platform: ecodan
    z2_flow_temp_target:
      id: z2_flow_temp_target
      name: Zone 2 H/C setpoint value
      # on_value:
      #   if:
      #     condition:
      #       - lambda: |-
      #           return id(heatpump_number_z2_set_flow_temperature).state != id(z2_flow_temp_target).state;
      #     then:
      #       - number.set:
      #           id: heatpump_number_z2_set_flow_temperature
      #           value: !lambda "return id(z2_flow_temp_target).state;"
    z2_room_temp:
      id: z2_room_temp
      name: Zone 2 room temp      
    z2_room_temp_target:
      id: z2_room_temp_target
      name: Zone 2 room setpoint value
      # on_value:
      #   if:
      #     condition:
      #       - lambda: |-
      #           return id(heatpump_number_z2_set_room_temperature).state != id(z2_room_temp_target).state;
      #     then:
      #       - number.set:
      #           id: heatpump_number_z2_set_room_temperature
      #           value: !lambda "return id(z2_room_temp_target).state;"