name: Build Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          python -m pip install wheel
          python -m pip install esphome
          echo "wifi_ssid: \"dummy\" " > secrets.yaml
          echo "wifi_password: \"dummy\" " >> secrets.yaml
          esphome compile ecodan-esphome.yaml
          cp .pioenvs/ecodan-heatpump/firmware.bin dist/firmware.bin

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
